apiVersion: v1
kind: Service
metadata:
  name: ephemeral-service
spec:
  type: NodePort
  selector:
    app: ephemeral-app
  ports:
    - port: 80
      targetPort: 8080
      # Omit nodePort to let Kubernetes assign a random one