replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: "#{Project.HelmChart.IngressHost}"
      paths:
        - path: /
          pathType: Prefix