apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seascape-core-dev
  annotations:
    argo.octopus.com/project: "seascape-core"
    argo.octopus.com/environment: "development"
    # When there is a single source, we use a single unscoped annotation to specify call paths
    argo.octopus.com/image-replace-paths: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    argo.octopus.com/instance: "demo.octopus.app"
spec:
  project: default
  source:
    repoURL: https://github.com/harrisonmeister/kubernetes-apps.git
    targetRevision: HEAD
    path: helm-charts/seascape-core
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: seascape-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true