apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-example.fullname" . }}
  labels:
    {{- include "helm-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
        {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
        {{- end }}
      {{- end }}
  selector:
    {{- include "helm-example.selectorLabels" . | nindent 4 }}