name: Docker Build & Push (terranova-web-app)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terranova-web-helm.yaml'
      - 'terranova-web/**'
  schedule:
    - cron: '0 6 * * 1-5' # Monday to Friday at 6:00 AM UTC
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
      id-token: write
      attestations: write
    
    env:
      DOCKER_USER: harrisonmeister
      IMAGE_NAME: terranova-web
      SBOM_OUTPUT_FILE: sbom.json
      SBOM_PACKAGE_NAME: terranova-web-sbom
      OCTOPUS_URL: ${{ vars.DEMO_OCTOPUS_URL }}
      OCTOPUS_SPACE: ${{ vars.DEMO_OCTOPUS_SPACE }}

    steps:
      - name: 1. Calculate Version Tag
        id: version
        run: |
          DATE=$(date +%Y.%m.%d)
          VERSION_TAG="${DATE}.${{ github.run_number }}"
          echo "tag=${VERSION_TAG}" >> $GITHUB_OUTPUT
          echo "Generated tag: $VERSION_TAG"

      - name: 2. Checkout repository
        uses: actions/checkout@v4

      - name: 3. Set up QEMU (for multi-platform)
        uses: docker/setup-qemu-action@v3

      - name: 4. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 5. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 6. Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 7. Determine tags (for Docker Hub and GHCR)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: 8. Build and Load Image Locally
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./terranova-web
          file: ./terranova-web/Dockerfile
          push: false
          load: true
          tags: ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest 
          platforms: linux/amd64
      
      - name: 9. Generate CycloneDX SBOM (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: '${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest'
          format: 'cyclonedx'
          output: ${{ env.SBOM_OUTPUT_FILE }}
          
      - name: 10. Zip SBOM Package for Octopus Deploy
        id: package
        run: |
          PACKAGE_ID="${{ env.SBOM_PACKAGE_NAME }}"
          VERSION="${{ steps.version.outputs.tag }}"
          ZIP_FILENAME="${PACKAGE_ID}.${VERSION}.zip"
          
          # Create a directory to ensure the zip is structured correctly
          mkdir -p packaging
          
          # Zip the SBOM file
          zip -j packaging/$ZIP_FILENAME ${{ env.SBOM_OUTPUT_FILE }}
          
          echo "package_file=packaging/$ZIP_FILENAME" >> $GITHUB_OUTPUT

      - name: 11. Login to Octopus Deploy 🐙
        uses: OctopusDeploy/login@v1
        with: 
          server: ${{ secrets.DEMO_OCTOPUS_URL }}
          service_account_id: 4d50c8ac-1515-4351-96a7-4a82d55d55ff
      
      - name: 12. Push SBOM Package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v3
        with:
          packages: |
            ${{ steps.package.outputs.package_file }}
      - name: Push build information to Octopus Deploy 🐙
        uses: OctopusDeploy/push-build-information-action@v3
        with:
          version: ${{ steps.version.outputs.tag }}
          packages: |
            ${{ env.SBOM-PACKAGE-NAME }}

      - name: 12. Attest Build Provenance for Docker Hub
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: false

      - name: 13. Attest Build Provenance for GHCR
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: false

      - name: 14. Final Push to Docker Hub and GHCR
        run: |
          LOCAL_TAG="${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest"
          ALL_TAGS="${{ steps.meta.outputs.tags }},${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }},ghcr.io/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }}"
          
          for TAG in $(echo $ALL_TAGS | sed "s/,/ /g"); do
            echo "Pushing $TAG"
            docker tag $LOCAL_TAG $TAG
            docker push $TAG
          done